common: 
  context: local
  cfgdir: foo
  logdir: bar
  tmpdir: baz 
  resultdir: ban
  log_level: debug
  log_retention: 14
  suiteid: suiteA_footag
  k8s_auth:
    user: foo
    password: bar
    url: https://foo/api/v2
  robocorp_auth:
    user: foo
    password: bar
    url: https://foo/api/v2
suites: 
  suiteA_footag: 
    target: local
    path: suiteA
    tag: footag
    piggybackhost: bazhost
    shared_python: false
    headless: true
    params:
      variables: 
        vara: a
        varb: b
    failed_handling:
      max_attempts: 2
    scheduling: 
      interval: 1
      allow_overlap: false
  suite-B:
    target: local
    path: suiteB
    shared_python: false
    scheduling: 
      interval: 2
      allow_overlap: false
  suite-C:
    target: remote
    scheduling: 
      interval: 2
  suite-D: 
    target: remote    
    scheduling: 
      interval: 4




